### ISSUE TITLE
Evidence of widespread metabolite abnormalities in Myalgic encephalomyelitis/chronic fatigue syndrome: assessment with whole-brain magnetic resonance spectroscopy

### ISSUE THREAD

**Issue by anka339** [fmachado/me-cfs#2]
*Title:*
Evidence of widespread metabolite abnormalities in Myalgic encephalomyelitis/chronic fatigue syndrome: assessment with whole-brain magnetic resonance spectroscopy

*Source (URL):*
https://pubmed.ncbi.nlm.nih.gov/30617782/

*DOI:*
10.1007/s11682-018-0029-4

**Comment by fmachado** [comment]
Resource added. Done.
